/**
 * Media removed from git and served by the worker from R2 binding MEDIA.
 * Bytes are recovered from sourceCommit via `git show`. Do not re-commit these files.
 * See docs/media-r2.md. R2 was not enabled in this environment (Cloudflare error 10042).
 */
export const R2_MEDIA_SOURCE_COMMIT = "f3b6cead70a13cf1ea137123861d23473f3cb87e";

export type R2MediaObject = {
  key: string;
  source: string;
  contentType: string;
  bytes: number;
};

export const R2_MEDIA_OBJECTS: R2MediaObject[] = [
  {
    key: "assets/archive-kuwait-cricket-news.jpg",
    source: "public/assets/archive-kuwait-cricket-news.jpg",
    contentType: "image/jpeg",
    bytes: 572438,
  },
  {
    key: "assets/beyond-techniques.mp4",
    source: "public/assets/beyond-techniques.mp4",
    contentType: "video/mp4",
    bytes: 11756471,
  },
  {
    key: "assets/cxo-magazine-april-2026.pdf",
    source: "public/assets/cxo-magazine-april-2026.pdf",
    contentType: "application/pdf",
    bytes: 15178829,
  },
  {
    key: "assets/osh-18.jpg",
    source: "public/assets/osh-18.jpg",
    contentType: "image/jpeg",
    bytes: 602771,
  },
  {
    key: "assets/osh-interview-reel/2025-06-11_11-37-35_UTC.mp4",
    source: "public/assets/osh-interview-reel/2025-06-11_11-37-35_UTC.mp4",
    contentType: "video/mp4",
    bytes: 1826210,
  },
  {
    key: "assets/osh-interview.mp4",
    source: "public/assets/osh-interview.mp4",
    contentType: "video/mp4",
    bytes: 6660880,
  },
  {
    key: "assets/osh-what-you-cant-predict-ar.pdf",
    source: "public/assets/osh-what-you-cant-predict-ar.pdf",
    contentType: "application/pdf",
    bytes: 4792639,
  },
  {
    key: "assets/quote-act.png",
    source: "public/assets/quote-act.png",
    contentType: "image/png",
    bytes: 1442307,
  },
  {
    key: "assets/superjet-dhofar.mp4",
    source: "public/assets/superjet-dhofar.mp4",
    contentType: "video/mp4",
    bytes: 1719777,
  },
  {
    key: "assets/superjet-dhofar/2025-07-26_08-33-00_UTC.mp4",
    source: "public/assets/superjet-dhofar/2025-07-26_08-33-00_UTC.mp4",
    contentType: "video/mp4",
    bytes: 1719777,
  },
  {
    key: "assets/team-ilmversity-1.jpg",
    source: "public/assets/team-ilmversity-1.jpg",
    contentType: "image/jpeg",
    bytes: 2866558,
  },
  {
    key: "assets/team-ilmversity-2.jpg",
    source: "public/assets/team-ilmversity-2.jpg",
    contentType: "image/jpeg",
    bytes: 2933910,
  },
  {
    key: "memoir/assets/audio/ch-01.mp3",
    source: "public/memoir/assets/audio/ch-01.mp3",
    contentType: "audio/mpeg",
    bytes: 4790637,
  },
  {
    key: "memoir/assets/audio/ch-01.spoken.js",
    source: "public/memoir/assets/audio/ch-01.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 3994,
  },
  {
    key: "memoir/assets/audio/ch-01.spoken.json",
    source: "public/memoir/assets/audio/ch-01.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 3966,
  },
  {
    key: "memoir/assets/audio/ch-02.mp3",
    source: "public/memoir/assets/audio/ch-02.mp3",
    contentType: "audio/mpeg",
    bytes: 5667885,
  },
  {
    key: "memoir/assets/audio/ch-02.spoken.js",
    source: "public/memoir/assets/audio/ch-02.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 4229,
  },
  {
    key: "memoir/assets/audio/ch-02.spoken.json",
    source: "public/memoir/assets/audio/ch-02.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 4201,
  },
  {
    key: "memoir/assets/audio/ch-03.mp3",
    source: "public/memoir/assets/audio/ch-03.mp3",
    contentType: "audio/mpeg",
    bytes: 4143213,
  },
  {
    key: "memoir/assets/audio/ch-03.spoken.js",
    source: "public/memoir/assets/audio/ch-03.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 3741,
  },
  {
    key: "memoir/assets/audio/ch-03.spoken.json",
    source: "public/memoir/assets/audio/ch-03.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 3713,
  },
  {
    key: "memoir/assets/audio/ch-04.mp3",
    source: "public/memoir/assets/audio/ch-04.mp3",
    contentType: "audio/mpeg",
    bytes: 4816557,
  },
  {
    key: "memoir/assets/audio/ch-04.spoken.js",
    source: "public/memoir/assets/audio/ch-04.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 4308,
  },
  {
    key: "memoir/assets/audio/ch-04.spoken.json",
    source: "public/memoir/assets/audio/ch-04.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 4280,
  },
  {
    key: "memoir/assets/audio/ch-05.mp3",
    source: "public/memoir/assets/audio/ch-05.mp3",
    contentType: "audio/mpeg",
    bytes: 4408173,
  },
  {
    key: "memoir/assets/audio/ch-05.spoken.js",
    source: "public/memoir/assets/audio/ch-05.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 3880,
  },
  {
    key: "memoir/assets/audio/ch-05.spoken.json",
    source: "public/memoir/assets/audio/ch-05.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 3852,
  },
  {
    key: "memoir/assets/audio/ch-06.mp3",
    source: "public/memoir/assets/audio/ch-06.mp3",
    contentType: "audio/mpeg",
    bytes: 4087341,
  },
  {
    key: "memoir/assets/audio/ch-06.spoken.js",
    source: "public/memoir/assets/audio/ch-06.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 3643,
  },
  {
    key: "memoir/assets/audio/ch-06.spoken.json",
    source: "public/memoir/assets/audio/ch-06.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 3615,
  },
  {
    key: "memoir/assets/audio/ch-07.mp3",
    source: "public/memoir/assets/audio/ch-07.mp3",
    contentType: "audio/mpeg",
    bytes: 5019885,
  },
  {
    key: "memoir/assets/audio/ch-07.spoken.js",
    source: "public/memoir/assets/audio/ch-07.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 4246,
  },
  {
    key: "memoir/assets/audio/ch-07.spoken.json",
    source: "public/memoir/assets/audio/ch-07.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 4218,
  },
  {
    key: "memoir/assets/audio/ch-08.mp3",
    source: "public/memoir/assets/audio/ch-08.mp3",
    contentType: "audio/mpeg",
    bytes: 4697325,
  },
  {
    key: "memoir/assets/audio/ch-08.spoken.js",
    source: "public/memoir/assets/audio/ch-08.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 4115,
  },
  {
    key: "memoir/assets/audio/ch-08.spoken.json",
    source: "public/memoir/assets/audio/ch-08.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 4087,
  },
  {
    key: "memoir/assets/audio/ch-09.mp3",
    source: "public/memoir/assets/audio/ch-09.mp3",
    contentType: "audio/mpeg",
    bytes: 3860397,
  },
  {
    key: "memoir/assets/audio/ch-09.spoken.js",
    source: "public/memoir/assets/audio/ch-09.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 3368,
  },
  {
    key: "memoir/assets/audio/ch-09.spoken.json",
    source: "public/memoir/assets/audio/ch-09.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 3340,
  },
  {
    key: "memoir/assets/audio/ch-10.mp3",
    source: "public/memoir/assets/audio/ch-10.mp3",
    contentType: "audio/mpeg",
    bytes: 4085037,
  },
  {
    key: "memoir/assets/audio/ch-10.spoken.js",
    source: "public/memoir/assets/audio/ch-10.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 3630,
  },
  {
    key: "memoir/assets/audio/ch-10.spoken.json",
    source: "public/memoir/assets/audio/ch-10.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 3602,
  },
  {
    key: "memoir/assets/audio/ch-11.mp3",
    source: "public/memoir/assets/audio/ch-11.mp3",
    contentType: "audio/mpeg",
    bytes: 3745197,
  },
  {
    key: "memoir/assets/audio/ch-11.spoken.js",
    source: "public/memoir/assets/audio/ch-11.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 3442,
  },
  {
    key: "memoir/assets/audio/ch-11.spoken.json",
    source: "public/memoir/assets/audio/ch-11.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 3414,
  },
  {
    key: "memoir/assets/audio/ch-12.mp3",
    source: "public/memoir/assets/audio/ch-12.mp3",
    contentType: "audio/mpeg",
    bytes: 7647021,
  },
  {
    key: "memoir/assets/audio/ch-12.spoken.js",
    source: "public/memoir/assets/audio/ch-12.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 5858,
  },
  {
    key: "memoir/assets/audio/ch-12.spoken.json",
    source: "public/memoir/assets/audio/ch-12.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 5830,
  },
  {
    key: "memoir/assets/audio/ch-13.mp3",
    source: "public/memoir/assets/audio/ch-13.mp3",
    contentType: "audio/mpeg",
    bytes: 5174253,
  },
  {
    key: "memoir/assets/audio/ch-13.spoken.js",
    source: "public/memoir/assets/audio/ch-13.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 4549,
  },
  {
    key: "memoir/assets/audio/ch-13.spoken.json",
    source: "public/memoir/assets/audio/ch-13.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 4521,
  },
  {
    key: "memoir/assets/audio/ch-14.mp3",
    source: "public/memoir/assets/audio/ch-14.mp3",
    contentType: "audio/mpeg",
    bytes: 4246893,
  },
  {
    key: "memoir/assets/audio/ch-14.spoken.js",
    source: "public/memoir/assets/audio/ch-14.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 3699,
  },
  {
    key: "memoir/assets/audio/ch-14.spoken.json",
    source: "public/memoir/assets/audio/ch-14.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 3671,
  },
  {
    key: "memoir/assets/audio/ch-15.mp3",
    source: "public/memoir/assets/audio/ch-15.mp3",
    contentType: "audio/mpeg",
    bytes: 4415661,
  },
  {
    key: "memoir/assets/audio/ch-15.spoken.js",
    source: "public/memoir/assets/audio/ch-15.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 4279,
  },
  {
    key: "memoir/assets/audio/ch-15.spoken.json",
    source: "public/memoir/assets/audio/ch-15.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 4251,
  },
  {
    key: "memoir/assets/audio/ch-16.mp3",
    source: "public/memoir/assets/audio/ch-16.mp3",
    contentType: "audio/mpeg",
    bytes: 7559469,
  },
  {
    key: "memoir/assets/audio/ch-16.spoken.js",
    source: "public/memoir/assets/audio/ch-16.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 6698,
  },
  {
    key: "memoir/assets/audio/ch-16.spoken.json",
    source: "public/memoir/assets/audio/ch-16.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 6670,
  },
  {
    key: "memoir/assets/audio/epilogue.mp3",
    source: "public/memoir/assets/audio/epilogue.mp3",
    contentType: "audio/mpeg",
    bytes: 7774893,
  },
  {
    key: "memoir/assets/audio/epilogue.spoken.js",
    source: "public/memoir/assets/audio/epilogue.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 6823,
  },
  {
    key: "memoir/assets/audio/epilogue.spoken.json",
    source: "public/memoir/assets/audio/epilogue.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 6795,
  },
  {
    key: "memoir/assets/audio/prologue.mp3",
    source: "public/memoir/assets/audio/prologue.mp3",
    contentType: "audio/mpeg",
    bytes: 7042221,
  },
  {
    key: "memoir/assets/audio/prologue.spoken.js",
    source: "public/memoir/assets/audio/prologue.spoken.js",
    contentType: "text/javascript; charset=utf-8",
    bytes: 5817,
  },
  {
    key: "memoir/assets/audio/prologue.spoken.json",
    source: "public/memoir/assets/audio/prologue.spoken.json",
    contentType: "application/json; charset=utf-8",
    bytes: 5789,
  },
  {
    key: "memoir/assets/audio/voice-deeper.mp3",
    source: "public/memoir/assets/audio/voice-deeper.mp3",
    contentType: "audio/mpeg",
    bytes: 647626,
  },
  {
    key: "memoir/assets/audio/voice-softer.mp3",
    source: "public/memoir/assets/audio/voice-softer.mp3",
    contentType: "audio/mpeg",
    bytes: 4528557,
  },
  {
    key: "memoir/assets/photos/ch01-born-1984.jpg",
    source: "public/memoir/assets/photos/ch01-born-1984.jpg",
    contentType: "image/jpeg",
    bytes: 795015,
  },
  {
    key: "memoir/assets/photos/ch02-kuwait-1986.jpg",
    source: "public/memoir/assets/photos/ch02-replace with niagra falls - kuw-1986.jpg",
    contentType: "image/jpeg",
    bytes: 1028997,
  },
  {
    key: "memoir/assets/photos/ch03-u19-tour-clipping-2001.jpg",
    source: "public/memoir/assets/photos/ch03-u19-tour-clipping-2001.jpg",
    contentType: "image/jpeg",
    bytes: 671361,
  },
  {
    key: "memoir/assets/photos/ch04-Motorola-project-meeting.jpg",
    source: "public/memoir/assets/photos/ch04-Motorola-project-meeting.jpg",
    contentType: "image/jpeg",
    bytes: 707074,
  },
  {
    key: "memoir/assets/photos/ch04-uk-leadership-dinner.jpg",
    source: "public/memoir/assets/photos/ch04-uk-leadership-dinner.jpg",
    contentType: "image/jpeg",
    bytes: 3515820,
  },
  {
    key: "memoir/assets/photos/ch04-warehouse-aramex-motorola oman.jpg",
    source: "public/memoir/assets/photos/ch04-warehouse-aramex-motorola oman.jpg",
    contentType: "image/jpeg",
    bytes: 3163275,
  },
  {
    key: "memoir/assets/photos/ch05-Gov-oman-site-visit.jpg",
    source: "public/memoir/assets/photos/ch05-Gov-oman-site-visit.jpg",
    contentType: "image/jpeg",
    bytes: 12795017,
  },
  {
    key: "memoir/assets/photos/ch06-huawei-bahrain-subcon.jpg",
    source: "public/memoir/assets/photos/ch06-add-HUW Bah Subcon.jpg",
    contentType: "image/jpeg",
    bytes: 798448,
  },
  {
    key: "memoir/assets/photos/ch07-kuwait-cricket.jpg",
    source: "public/memoir/assets/photos/ch07-replace with kuwait cricket image.jpg",
    contentType: "image/jpeg",
    bytes: 1102581,
  },
  {
    key: "memoir/assets/photos/ch08-huawei-bahrain-2018.jpg",
    source: "public/memoir/assets/photos/ch08-replace with huawei bah day image .jpg",
    contentType: "image/jpeg",
    bytes: 713095,
  },
  {
    key: "memoir/assets/photos/ch08-huawei-best-mentor-award.jpg",
    source: "public/memoir/assets/photos/ch08-add-Huw best mentor award.jpg",
    contentType: "image/jpeg",
    bytes: 1554482,
  },
  {
    key: "memoir/assets/photos/ch08-msi-event.png",
    source: "public/memoir/assets/photos/ch08-msi-event.png",
    contentType: "image/png",
    bytes: 1856953,
  },
  {
    key: "memoir/assets/photos/ch09-pyramid.png",
    source: "public/memoir/assets/photos/ch09-pyramid.png",
    contentType: "image/png",
    bytes: 7085292,
  },
  {
    key: "memoir/assets/photos/ch11-site-visit-OM.jpg",
    source: "public/memoir/assets/photos/ch11-site-visit-OM.jpg",
    contentType: "image/jpeg",
    bytes: 567033,
  },
  {
    key: "memoir/assets/photos/ch11-super-labor-site-visit.jpg",
    source: "public/memoir/assets/photos/ch11-add-Super labor - site visit-.jpg",
    contentType: "image/jpeg",
    bytes: 1572290,
  },
  {
    key: "memoir/assets/photos/ch13-oman-digital-drift-workshop.jpg",
    source: "public/memoir/assets/photos/ch13-oman-digital-drift-workshop.jpg",
    contentType: "image/jpeg",
    bytes: 1441677,
  },
  {
    key: "memoir/assets/photos/ch14-umrah-friends-2024.jpg",
    source: "public/memoir/assets/photos/ch14-add-umrah-frnds-2024.jpg",
    contentType: "image/jpeg",
    bytes: 2288260,
  },
  {
    key: "memoir/assets/photos/ch15-children-uk-2023.jpg",
    source: "public/memoir/assets/photos/ch15-add-Children in UK 2023.jpg",
    contentType: "image/jpeg",
    bytes: 3337685,
  },
  {
    key: "memoir/assets/photos/epilogue-40th-birthday.jpg",
    source: "public/memoir/assets/photos/epilogue-40th-birthday.jpg",
    contentType: "image/jpeg",
    bytes: 6230124,
  },
];
